import Head from 'next/head'
import Banner from '../components/Banner'
// import Introduction from '../components/Introduction'
import Navbar from '../components/Navbar'
import AboutMeAndServices from '../components/AboutMeAndServices'
import styles from '../styles/Home.module.css'
import Technologies from '../components/Technologies'
import Projects from '../components/Projects'
import ContactMe from '../components/ContactMe'
import Footer from '../components/Footer'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Lee Effect</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar />
      <Banner />
      {/* <Introduction /> */}
      <AboutMeAndServices />
      <Technologies />
      <Projects />
      <ContactMe />
      <Footer />

      
    </div>
  )
}
